name:                Learning
version:             0.1.0
github:              "masterdezign/Learning"
license:             BSD3
author:              "Bogdan Penkovsky"
maintainer:          "dev () penkovsky dot com"
copyright:           "Bogdan Penkovsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            The most frequently used machine learning tools
category:            Machine Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/masterdezign/Learning#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hmatrix >= 0.18.1.0
- vector
- streamly >= 0.4.0

library:
  source-dirs: src

executables:
  learning-pca:
    main:                Main.lhs
    source-dirs:         examples/PCA
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Learning

  learning-pca-advanced:
    main:                Main.lhs
    source-dirs:         examples/PCA2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Learning

  learning-ridge-regression:
    main:                Main.hs
    source-dirs:         examples/Ridge
    dependencies:
    - bytestring
    - Learning

tests:
  Learning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Learning

benchmarks:
  Learning-bench:
    main: Bench.hs
    source-dirs:
    - bench
    - src
    dependencies:
    - criterion
    - deepseq
